import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./styles/reset.css";

const raleway = Raleway({ weight: ['300', '400', '500', '600', '700'], subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
